name: Test
on: workflow_dispatch
jobs:
  install:
    name: Test the action
    runs-on: windows-latest
    steps:
      - name: Checkout content repository
        uses: actions/checkout@v3
        with:
          repository: 'lol-tracker/content'
          path: 'content'
