name: Test
on: workflow_dispatch
jobs:
  install:
    name: Test the action
    #runs-on: windows-latest
    steps:
      # - name: Add github.com to known hosts
      #   shell: bash
      #   run: |
      #     mkdir ~/.ssh/
      #     ssh-keyscan github.com >> ~/.ssh/known_hosts
      - name: Checkout content repository
        uses: actions/checkout@v3
        with:
          repository: 'lol-tracker/content'
          ssh-key: ${{ secrets.CONTENT_SSH_PRIVATE_KEY }}
          ssh-strict: false
          path: 'content'
      - name: Done
        run: echo Done
