name: Update the content
on:
  workflow_dispatch:
  workflow_call:
    secrets:
      LOL_USERNAME:
        required: true
      LOL_PASSWORD:
        required: true
      LOL_REGION:
        required: true
      CONTENT_SSH_PRIVATE_KEY:
        required: true
jobs:
  update:
    runs-on: windows-latest
    steps:
      - name: Setup the League Client
        id: league-client
        uses: lol-tracker/setup-league-client@latest
        with:
          username: ${{ secrets.LOL_USERNAME }}
          password: ${{ secrets.LOL_PASSWORD }}
          region: ${{ secrets.LOL_REGION }}
      - name: Checkout watchdog repository
        uses: actions/checkout@v3
        with:
          path: 'watchdog'
      - name: Checkout content repository
        uses: actions/checkout@v3
        with:
          repository: 'lol-tracker/content'
          ssh-key: ${{ secrets.CONTENT_SSH_PRIVATE_KEY }}
          path: 'content'
      - name: Parse the content
        shell: pwsh
        working-directory: content
        run: '& ../watchdog/scripts/Update.ps1'
        env:
          RCS_PASSWORD: ${{ steps.league-client.outputs.rcs-password }}
          RCS_PORT: ${{ steps.league-client.outputs.rcs-port }}
          RCS_DIR: ${{ steps.league-client.outputs.rcs-directory }}
          LCU_PASSWORD: ${{ steps.league-client.outputs.lcu-password }}
          LCU_PORT: ${{ steps.league-client.outputs.lcu-port }}
          LCU_DIR: ${{ steps.league-client.outputs.lcu-directory }}
      - name: Commit and push new content
        working-directory: content
        # TODO: Proper commit name
        run: |
          git config --global user.email "github-action-${{github.actor}}@users.noreply.github.com"
          git config --global user.name "lol-tracker-bot"
          git add .
          git commit -m "Updated to version $(cat lol/version.txt | cut -d "\"" -f 2)"
          git push


