name: Update the content
on:
  workflow_dispatch:
    inputs:
      push_update:
        description: 'Should we push update to github?'
        required: false
        default: true
        type: boolean
  workflow_call:
    inputs:
      LOL_USERNAME:
        required: true
        type: string
      LOL_PASSWORD:
        required: true
        type: string
      LOL_REGION:
        required: true
        type: string
      LOL_PATCHLINE:
        required: false
        default: 'live'
        type: string
      LOL_CONFIG:
        required: false
        default: ''
        type: string
jobs:
  update:
    runs-on: windows-latest
    steps:
      - name: Checkout watchdog repository
        uses: actions/checkout@v4
        with:
          path: 'watchdog'
      - name: Checkout content repository
        uses: actions/checkout@v4
        with:
          repository: 'lol-tracker/content'
          ssh-key: ${{ secrets.CONTENT_SSH_PRIVATE_KEY }}
          ref: ${{ github.ref_name }}
          path: 'content'
      # - name: Change content branch
      #   if: ${{ github.ref_name != 'main' }}
      #   path: 'content'
      #   run: git switch -C ${{ github.ref_name }}
      - name: Setup the League Client
        id: league-client
        uses: lol-tracker/setup-league-client@latest
        with:
          username: ${{ github.event_name == 'workflow_call' && inputs.LOL_USERNAME || secrets.LOL_USERNAME }}
          password: ${{ github.event_name == 'workflow_call' && inputs.LOL_PASSWORD || secrets.LOL_PASSWORD }}
          region: ${{ github.event_name == 'workflow_call' && inputs.LOL_REGION || secrets.LOL_REGION }}
          patchline: ${{ github.event_name == 'workflow_call' && inputs.LOL_PATCHLINE || 'live' }}
          config: ${{ github.event_name == 'workflow_call' && inputs.LOL_CONFIG || '' }}
          install-pengu: true
      - name: Parse the content
        shell: pwsh
        working-directory: content
        run: '& ../watchdog/updater/update.ps1'
        env:
          RCS_PASSWORD: ${{ steps.league-client.outputs.rcs-password }}
          RCS_PORT: ${{ steps.league-client.outputs.rcs-port }}
          RCS_DIR: ${{ steps.league-client.outputs.rcs-directory }}
          LCU_PASSWORD: ${{ steps.league-client.outputs.lcu-password }}
          LCU_PORT: ${{ steps.league-client.outputs.lcu-port }}
          LCU_DIR: ${{ steps.league-client.outputs.lcu-directory }}
          PENGU_DIR: ${{ steps.league-client.outputs.pengu-directory }}
      - name: Commit and push new content
        if: ${{ github.event_name == 'workflow_call' || github.event.inputs.push_update == 'true' }}
        working-directory: content
        run: |
          git config --global user.email "github-action-${{github.actor}}@users.noreply.github.com"
          git config --global user.name "lol-tracker-bot"
          git add .
          $ver = (Get-Content 'lol/version.txt' | ConvertFrom-Json).client
          git commit -m "Updated to version $ver"
          git push
